# Generated by Django 5.1.4 on 2024-12-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_topic_choose_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Choose_image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
